#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allclean
./Allrun.pre

#Running changedict
listsolid=$(egrep "solid" ./constant/regionProperties | egrep -o '\(.*\)' | sed -e 's:(::' -e 's:)::')
listfluid=$(egrep "fluid" ./constant/regionProperties | egrep -o '\(.*\)' | sed -e 's:(::' -e 's:)::')


#Running face agglomerate in parallel
for i in $listfluid; do
    runApplication -s "$i" \
        faceAgglomerate -region "$i" -dict constant/viewFactorsDict
done

# Generate view factors
for i in $listfluid; do
    runApplication -s "$i" \
        viewFactorsGen -region "$i"
done

# Run
runApplication `getApplication`

## Reconstruct
#runApplication reconstructPar -allRegions
#
